name: Terraform tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  terraform-tests:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.1.6"
      - name: Terraform tests
        env:
          GH_EVENT: ${{ toJSON(github.event) }}
        run: |
          pr_branch=$(jq -r '.pull_request.head.ref' <<< "${GH_EVENT}")
          path=$(gh pr diff --name-only "${pr_branch}")
          echo "${path}"
