name: Terraform tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  terraform-tests:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Terraform tests
        env:
          GH_EVENT: ${{ toJSON(github.event) }}
        run: |
          pr_branch=$(jq -r '.pull_request.head.ref' <<< "${GH_EVENT}")
          gh pr diff --name-only "${pr_branch}" | grep '^infra/modules/.*\/tests/' | cut -d/ -f3
