name: Terratest

on:
  workflow_dispatch:
    inputs:
      working_directory:
        description: "Test Working Directory."
        required: true
        type: string

jobs:
  terraform-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
      - uses: actions/setup-go@v1
        with:
          go-version: 1.21.1
      - name: Download Go Modules
        working-directory: infra/modules/security/tests
        run: go mod download
      - name: Run tests
        working-directory: infra/modules/security/tests
        run: go test -v
