name: Terraform tests

on:
  pull_request:
    paths:
      - "*/terraform/modules/**"
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  terraform-tests:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get modified module folders
        id: get_module_folders
        env:
          GH_EVENT: ${{ toJSON(github.event) }}
        run: |
          MODULE_FOLDERS=$(gh pr diff --name-only ${{ github.event.number }} | grep -oP '^([^/]*/terraform/modules/[^/]*)(?=/)' | sort | uniq)  
          echo "$MODULE_FOLDERS"        
          {
          echo 'folders<<EOF'
          echo "$MODULE_FOLDERS"
          echo EOF 
          } >> $GITHUB_OUTPUT
      - name: Run Terraform tests
        run: |
          MODULE_FOLDERS="${{ steps.get_module_folders.outputs.folders }}"
          while IFS= read -r line; do
              echo "{\"working_directory\":\"$line/tests\"}" | gh workflow run terratest.yaml --json
          done <<< "$MODULE_FOLDERS"
