name: Terraform tests

on:
  pull_request:
    - opened
    - reopened
    - edited
    - synchronize

jobs:
  terraform-tests:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Terraform tests
        env:
          GH_EVENT: ${{ toJSON(github.event) }}
        run: echo "Hello World"
